workspace 1 output $fm
workspace 2 output $fm
workspace 3 output $fm
workspace 4 output $fm

workspace 5 output $sm
workspace 6 output $sm
workspace 7 output $sm
workspace 8 output $sm

workspace 9 output $mm
workspace 10 output $mm
workspace 11 output $mm
workspace 12 output $mm

# Define workspace Vars
set $ws1 1
set $ws2 "2 : Firefox"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"
set $ws11 "11"
set $ws12 "12"


